# -*- coding: utf-8 -*-
"""wavepad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107UzH8ughW3Uqa2nfPHRkqk3SU5auKDT
"""

!sudo apt install espeak-ng # Install espeak-ng text-to-speech engine
!pip install pydub
!pip install pyttsx3 # Install the pyttsx3 library

import librosa
import numpy as np
import pyttsx3
from pydub import AudioSegment
from IPython.display import Audio

# Initialize text-to-speech engine
engine = pyttsx3.init()

# Function to speak text and save to WAV file
def speak(text, filename="output.wav"):
    engine.save_to_file(text, filename)
    engine.runAndWait()

audio_path = '/content/output.wav.mp3'  # Path to the file

try:
    # Load the audio file
    y, sr = librosa.load(audio_path)
    if y is None or len(y) == 0:
        raise ValueError("The audio data is empty or not loaded properly.")

    speak("Audio loaded successfully!")
    Audio("output.wav", autoplay=True) # Play the output audio

    # Basic information
    sampling_rate_message = f"Sampling rate is {sr} hertz."
    audio_shape_message = f"The shape of the audio data is {y.shape[0]} samples."
    speak(sampling_rate_message, filename="sampling_rate.wav")
    Audio("sampling_rate.wav", autoplay=True) # Play the output audio
    speak(audio_shape_message, filename="audio_shape.wav")
    Audio("audio_shape.wav", autoplay=True) # Play the output audio

    # ... (Rest of your code with similar modifications for audio output)

except FileNotFoundError:
    error_message = f"File {audio_path} not found. Please check the file path."
    speak(error_message, filename="error.wav")
    Audio("error.wav", autoplay=True) # Play the output audio

except Exception as e:
    error_message = f"An error occurred: {str(e)}"
    speak(error_message, filename="error.wav")
    Audio("error.wav", autoplay=True) # Play the output audio